MultiAplicationForIS.WebUI/Pages/AddUser.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MultiAplicationForIS.BLForAPI;
using MultiAplicationForIS.Core.Interfaces;

namespace MultiAplicationForIS.WebUI.Pages
{
    public class AddUserModel : PageModel
    {

        private readonly IUserService _IUserService;
        private readonly ILogger<IndexModel> _logger;

        public string Message { get; private set; }
        public AddUserModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            _IUserService = new APIUserService();
        }


        public void OnPostAddUser(string name , string login, string password)
        {
            try
            {
                _IUserService.AddUser(name, password, login);
                Message = "Done";
            }
            catch (Exception ex)
            {
                Message = ex.Message;
            }
        }
    }
}

MultiAplicationForIS.WebUI/Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace MultiAplicationForIS.WebUI.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

MultiAplicationForIS.WebUI/Pages/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using MultiAplicationForIS.BLForAPI;
using MultiAplicationForIS.Core.Interfaces;

namespace MultiAplicationForIS.WebUI.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        private readonly IUserService _IUserService;

        public string Message { get; private set; }


        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
            _IUserService = new APIUserService(); // todo  плохо  
        }

        public void OnGet()
        {
           
        }
        public void OnPostLogIn(string login, string password)
        {
            try
            {
               var us =   _IUserService.GetUser(login, password);
                if (us != null)
                {
                    Message = "Привет " + us.Name; 
                }
            }
            catch (Exception ex)
            {
                Message = ex.Message;
            }


        }



    }
}

MultiAplicationForIS.WebUI/Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace MultiAplicationForIS.WebUI.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

MultiAplicationForIS.WebUI/Pages/AddUser.cshtml
@page
@model MultiAplicationForIS.WebUI.Pages.AddUserModel
@{
}

<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">

<div class="container-fluid">
    <div class="col-md-4 offset-md-4">
        <div class="form-container">
            <div class="form-icon"><i class="fa fa-user"></i></div>
            <h3 class="title">Регисрация</h3>
            <form class="form-horizontal" method="post">
                <div class="form-group">
                    <label>Имя</label>
                    <input class="form-control" type="text" name="name" placeholder="email address">
                </div>

                <div class="form-group">
                    <label>email</label>
                    <input class="form-control" type="email" name="login" placeholder="email address">
                </div>
                <div class="form-group">
                    <label>password</label>
                    <input class="form-control" type="password" name="password" placeholder="password">
                </div>
                <button type="submit" asp-page-handler="AddUser" class="btn btn-default">Регистрация</button>
            </form>
        </div>
    </div>

    <h1>@Model.Message</h1>

</div>

MultiAplicationForIS.WebUI/Pages/Index.cshtml
@page
@model IndexModel
@{
    ViewData["Title"] = "Home page";
}

<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" />
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0-beta3/css/all.min.css">


<div class="container-fluid">
    <div class="col-md-4 offset-md-4">
        <div class="form-container">
            <div class="form-icon"><i class="fa fa-user"></i></div>
            <h3 class="title">Login</h3>
            <form class="form-horizontal" method="post">
                <div class="form-group">
                    <label>email</label>
                    <input class="form-control" type="email" name="login"  placeholder="email address">
                </div>
                <div class="form-group">
                    <label>password</label>
                    <input class="form-control" type="password" name="password" placeholder="password">
                </div>
                <button type="submit" asp-page-handler="LogIn" class="btn btn-default">Login</button>
            </form>
        </div>
    </div>

    <h1>@Model.Message</h1>

</div>

MultiAplicationForIS.WebUI/Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MultiAplicationForIS.WebUI</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MultiAplicationForIS.WebUI.styles.css" asp-append-version="true" />
</head>

<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/Index">Авторизация</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-page="/AddUser">Регистрация</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - MultiAplicationForIS.WebUI - <a asp-area="" asp-page="/Privacy">Privacy</a>
        </div>
    </footer>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>